name: OWN A RADIO

on:
  push:
  pull_request:
    branches: master

jobs:
  push-to-server:

    runs-on: ubuntu-latest
    # needs: [tests, js-tests]
    steps:
    - uses: actions/checkout@v1

    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.KEY }}
        PORT: 22
      with:
        source: "."
        target: "/var/www/radio"

    # RUN ONLY THE FIRST TIME
    - name: Executing remote  command
      uses: appleboy/ssh-action@master
      with:
       host: ${{ secrets.HOST }}
       USERNAME: ${{ secrets.USERNAME }}
       KEY: ${{ secrets.KEY }}
       PORT: 22
       script: |
        cd /var/www/radio
        cp .env.prod .env
        composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --ignore-platform-reqs
        php artisan optimize:clear
        php artisan key:generate
        php artisan migrate --force --no-interaction
        php artisan storage:link
        php artisan optimize
        sudo usermod -aG radio www-data
        sudo chown -R radio:radio .
        sudo chmod -R 755 /var/www/radio
